(define (cube-iter guess x)
  (if (good-enough? guess x)
      guess
      (cube-iter (improve guess x) x)))
(define (improve guess x)
  (/ (+ (/ x (square guess)) (* 2 guess)) 3))
(define (square x)
  (* x x))
(define (good-enough? guess x)
  (< (abs (- guess (/ x guess guess))) 0.001))
(define (cube x)
  (cube-iter 1.0 x))
